# Generated by Django 5.0.7 on 2024-07-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='tipo_habitacion',
            field=models.CharField(choices=[('doble', 'habitacion doble'), ('triple', 'habitacion triple'), ('simple', 'habitacion francesa'), ('cuadruple', 'habitacion familiar')], default='simple', max_length=10),
        ),
    ]
