# Generated by Django 5.0.7 on 2024-07-27 14:01

import cleanmanager.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanmanager', '0002_alter_habitacion_tipo_habitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionlimpieza',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'limpieza pendiente'), ('proceso', 'limpieza en proceso'), ('completada', 'limpieza completada'), ('cancelada', 'limpieza cancelada')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(max_length=100, validators=[cleanmanager.validators.validar_nombre]),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(max_length=10, validators=[cleanmanager.validators.validar_telefono]),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='tipo_habitacion',
            field=models.CharField(choices=[('simple', 'habitacion francesa'), ('doble', 'habitacion doble'), ('triple', 'habitacion triple'), ('cuadruple', 'habitacion familiar')], default='simple', max_length=10),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='num_habitaciones',
            field=models.IntegerField(validators=[cleanmanager.validators.validar_habitaciones]),
        ),
    ]
