# Generated by Django 5.0.7 on 2024-07-28 01:34

import cleanmanager.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanmanager', '0003_alter_asignacionlimpieza_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacionlimpieza',
            name='fecha_asignacion',
        ),
        migrations.AddField(
            model_name='asignacionlimpieza',
            name='fecha_creado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='asignacionlimpieza',
            name='fecha_modificado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='empleado',
            name='dni',
            field=models.CharField(default='', max_length=20, validators=[cleanmanager.validators.validar_numero]),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='estado_habitacion',
            field=models.CharField(choices=[('libre', 'habitacion libre'), ('ocupada', 'habitacion ocupada')], default='libre', max_length=20),
        ),
        migrations.AlterField(
            model_name='asignacionlimpieza',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'limpieza pendiente'), ('enproceso', 'limpieza en proceso'), ('completada', 'limpieza completada'), ('cancelada', 'limpieza cancelada')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='tipo_habitacion',
            field=models.CharField(choices=[('simple', 'habitacion francesa'), ('doble', 'habitacion doble'), ('triple', 'habitacion triple'), ('cuadruple', 'habitacion familiar')], default='simple', max_length=20),
        ),
    ]
